FROM docker.elastic.co/kibana/kibana:5.6.3

#ADD kibana.yml /usr/share/kibana/config/

ENV ELASTICSEARCH_URL http://cellar.hub.log.elasticsearch:9200

# ENV XPACK_GRAPH_ENABLED=false
# ENV XPACK_MONITORING_ENABLED=false
# ENV XPACK_REPORTING_ENABLED=false
# ENV XPACK_SECURITY_ENABLED=false

EXPOSE 5601