version: '2'

services:
  cellar.hub.api:
    image: cellar.hub.api
    build:
      context: .
      dockerfile: Dockerfile_Cellar.Hub.Api
    links:
      - fluentd
      - cellar.hub.mongodb
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.api
    ports:
    - "8885:8885"

  cellar.hub.mongodb:
    image: cellar.hub.mongodb
    build: 
      context: ./Cellar.Hub.Db/mongodb
      dockerfile: Dockerfile
    ports:
    - "27017:27017"
    volumes:
     - /data/cellarstone.hub/mongodb:/data/db 
  

# don't rename to the cellar.hub.** pattern
# some stuffs with elaticsearch require the simple name pattern


  fluentd:
    build: ./Cellar.Hub.Log/fluentd
    volumes:
      - ./Cellar.Hub.Log/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch
    volumes:
        - /data/cellarstone.hub/elasticsearch:/var/lib/elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  prometheus:
    image: cellar.prometheus
    build:
      context: ./Cellar.Hub.Log/prometheus
      dockerfile: Dockerfile
    volumes:
      - /data/cellarstone.hub/prometheus:/prometheus
    ports:
      - '9090:9090'
    links:
      - pushgateway
    
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana
    volumes:
      - /data/cellarstone.hub/grafana:/var/lib/grafana
    ports:
      - '3000:3000'
