version: '2'

services:
  cellar.hub.web:
    image: cellar.hub.web
    build:
      context: ./Cellar.Hub.Web
      dockerfile: Dockerfile
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.web
    ports:
    - "44401:44401"

  # cellar.hub.admin:
  #   image: cellar.hub.admin
  #   build:
  #     context: ./Cellar.Hub.Admin
  #     dockerfile: Dockerfile
  #   links:
  #     - fluentd
  #   logging:
  #     driver: "fluentd"
  #     options:
  #       fluentd-address: localhost:24224
  #       tag: docker.cellar.hub.admin
  #   ports:
  #   - "44402:44402"

  cellar.hub.api:
    image: cellar.hub.api
    build:
      context: ./Cellar.Hub.Api
      dockerfile: Dockerfile
    links:
      - fluentd
      - cellar.hub.mongodb
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.api
    ports:
    - "44403:44403"

  cellar.hub.cdn:
    image: cellar.hub.cdn
    build:
      context: ./Cellar.Hub.Cdn
      dockerfile: Dockerfile
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.cdn
    ports:
    - "44404:44404"
    volumes:
     - /data/cellarstone.hub/cdn:/app/data

  cellar.hub.workflow:
    image: cellar.hub.workflow
    build:
      context: ./Cellar.Hub.Workflow
      dockerfile: Dockerfile
    links:
      - cellar.hub.mongodb
      - fluentd
      - pushgateway
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.workflow
    ports:
      - "44405:44405"

  cellar.hub.websockets:
    image: cellar.hub.websockets
    build:
      context: ./Cellar.Hub.Websockets
      dockerfile: Dockerfile
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.websockets
    ports:
    - "44406:44406"

  cellar.hub.mongodb:
    image: cellar.hub.mongodb
    build: 
      context: ./Cellar.Hub.Db/mongodb
      dockerfile: Dockerfile
    ports:
    - "27017:27017"
    volumes:
     - /data/cellarstone.hub/mongodb:/data/db 

  cellar.hub.mqtt:
    image: cellar.hub.mqtt
    build: 
      context: ./Cellar.Hub.Mqtt
      dockerfile: Dockerfile
    ports:
    - "1883:1883"

# don't rename to the cellar.hub.** pattern
# some stuffs with elaticsearch require the simple name pattern

  fluentd:
    image: cellar.hub.fluentd
    build: ./Cellar.Hub.Log/fluentd
    volumes:
      - ./Cellar.Hub.Log/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch
    volumes:
        - /data/cellarstone.hub/elasticsearch:/var/lib/elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  prometheus:
    image: cellar.hub.prometheus
    build:
      context: ./Cellar.Hub.Log/prometheus
      dockerfile: Dockerfile
    volumes:
      - /data/cellarstone.hub/prometheus:/data/prometheus
    ports:
      - '9090:9090'
    links:
      - pushgateway
    
  #prometheus pushgateway
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana
    links:
      - prometheus
      - elasticsearch
    volumes:
      - /data/cellarstone.hub/grafana:/var/lib/grafana
    ports:
      - '3000:3000'

  sysmon:
    image: titpetric/netdata
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    ports:
      - '19999:19999'