version: '2'

services:
  cellar.hub.web:
    image: cellar.hub.web
    build:
      context: .
      dockerfile: Dockerfile_Cellar.Hub.Web
    links:
      - cellar.hub.db
    ports:
    - "5001:5001"

  cellar.hub.dataflow:
    image: cellar.hub.dataflow
    build:
      context: .
      dockerfile: Dockerfile_Cellar.Hub.DataFlow
    links:
      - cellar.hub.db
      - cellar.hub.mqtt

  cellar.hub.db:
    image: cellar.hub.db
    build: 
      context: ./Cellar.Hub.Db
      dockerfile: Dockerfile
    ports:
    - "27017:27017"

  cellar.hub.mqtt:
    image: cellar.hub.mqtt
    build: 
      context: ./Cellar.Hub.Mqtt
      dockerfile: Dockerfile
    ports:
    - "1883:1883"
