version: '2'

services:

  cellar.hub.proxy:
    image: mynginx
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    links:
        - cellar.hub.web
        - cellar.hub.admin
    ports:
      - 8080:8080
      - 8081:8081

  cellar.hub.core.web:
    image: cellar.hub.core.web
    build:
      context: ./Core/Web
      dockerfile: Dockerfile
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.core.web
    ports:
    - "44401:44401"

  cellar.hub.core.admin:
    image: cellar.hub.core.admin
    build:
      context: ./Core/Admin
      dockerfile: Dockerfile
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.core.admin
    ports:
    - "44402:44402"

  cellar.hub.core.api:
    image: cellar.hub.core.api
    build:
      context: ./Core/Api
      dockerfile: Dockerfile
    links:
      - fluentd
      - cellar.hub.mongodb
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.core.api
    ports:
    - "44403:44403"

  cellar.hub.core.cdn:
    image: cellar.hub.core.cdn
    build:
      context: ./Core/Cdn
      dockerfile: Dockerfile
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.core.cdn
    ports:
    - "44404:44404"
    volumes:
     - c:/data/cellarstone.hub/core/cdn:/app/data

  cellar.hub.core.workflow:
    image: cellar.hub.core.workflow
    build:
      context: ./Core/Workflow
      dockerfile: Dockerfile
    links:
      - cellar.hub.mongodb
      - fluentd
      - pushgateway
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.core.workflow
    ports:
      - "44405:44405"

  cellar.hub.core.websockets:
    image: cellar.hub.core.websockets
    build:
      context: ./Core/Websockets
      dockerfile: Dockerfile
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.core.websockets
    ports:
    - "44406:44406"

# don't rename to the cellar.hub.** pattern
# some stuffs with elaticsearch require the simple name pattern

  mongodb:
    image: cellar.hub.mongodb
    build: 
      context: ./Core/Db/mongodb
      dockerfile: Dockerfile
    ports:
    - "27017:27017"
    volumes:
     - c:/data/cellarstone.hub/core/mongodb:/data/db 

  mqtt:
    image: cellar.hub.mqtt
    build: 
      context: ./Core/Mqtt
      dockerfile: Dockerfile
    ports:
    - "1883:1883"

  fluentd:
    image: cellar.hub.fluentd
    build: ./Core/Log/fluentd
    volumes:
      - ./Core/Log/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch
    volumes:
        - c:/data/cellarstone.hub/core/elasticsearch:/var/lib/elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  prometheus:
    image: cellar.hub.prometheus
    build:
      context: ./Core/Db/prometheus
      dockerfile: Dockerfile
    volumes:
      - c:/data/cellarstone.hub/core/prometheus:/data/prometheus
    ports:
      - '9090:9090'
    links:
      - pushgateway
    
  #prometheus pushgateway
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana
    links:
      - prometheus
      - elasticsearch
    volumes:
      - c:/data/cellarstone.hub/core/grafana:/var/lib/grafana
    ports:
      - '3000:3000'

  sysmon:
    image: titpetric/netdata
    cap_add:
      - SYS_PTRACE
    volumes:
      - c:/proc:/host/proc:ro
      - c:/sys:/host/sys:ro
    ports:
      - '19999:19999'