version: '2'

services:
  cellar.hub.web:
    image: cellar.hub.web
    build:
      context: .
      dockerfile: Dockerfile_Cellar.Hub.Web
    ports:
    - "5001:5001"

  cellar.hub.api:
    image: cellar.hub.api
    build:
      context: .
      dockerfile: Dockerfile_Cellar.Hub.Api
    links:
      - cellar.hub.mongodb
    ports:
    - "5005:5005"

  cellar.hub.mongodb:
    image: cellar.hub.mongodb
    build: 
      context: ./Cellar.Hub.MongoDb
      dockerfile: Dockerfile
    ports:
    - "27017:27017"
    volumes:
     - /data/db1:/data/db 

  cellar.hub.rethinkdb:
    image: cellar.hub.rethinkdb
    build: 
      context: ./Cellar.Hub.RethinkDb
      dockerfile: Dockerfile
    ports:
    - "28015:28015"
    - "29015:29015"
    - "8080:8080"
    volumes:
     - /data/db2:/data

  cellar.hub.mqtt:
    image: cellar.hub.mqtt
    build: 
      context: ./Cellar.Hub.Mqtt
      dockerfile: Dockerfile
    ports:
    - "1883:1883"

  cellar.hub.dataflow:
    image: cellar.hub.dataflow
    build:
      context: .
      dockerfile: Dockerfile_Cellar.Hub.DataFlow
    links:
      - cellar.hub.mqtt
      - cellar.hub.mongodb
      - cellar.hub.rethinkdb

  cellar.hub.websockets:
    image: cellar.hub.websockets
    build:
      context: ./Cellar.Hub.WebSockets
      dockerfile: Dockerfile
    links:
      - cellar.hub.rethinkdb
