version: '2'

#podle https://github.com/kzk/docker-compose-efk

services:
  cellar.hub.workflow:
    image: cellar.hub.workflow
    build:
      context: ./Cellar.Hub.Workflow
      dockerfile: Dockerfile
    # depends_on: 
    #   - cellar.hub.mongodb
    #   - cellar.hub.mqtt
    #   - fluentd
    #   - pushgateway
    #   - elasticsearch
    #   - kibana
    links:
      - fluentd
      - pushgateway
      - cellar.hub.mongodb
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.cellar.hub.workflow
    ports:
      - "5000:5000"

  cellar.hub.mongodb:
    image: cellar.hub.mongodb
    build: 
      context: ./Cellar.Hub.Db/mongodb
      dockerfile: Dockerfile
    ports:
    - "27017:27017"
    volumes:
        - /data/cellarstone.hub/mongodb:/data/db 

  cellar.hub.mqtt:
    image: cellar.hub.mqtt
    build: 
      context: ./Cellar.Hub.Mqtt
      dockerfile: Dockerfile
    ports:
    - "1883:1883"
  

# don't rename to the cellar.hub.** pattern
# some stuffs with elaticsearch require the simple name pattern


  fluentd:
    build: ./Cellar.Hub.Log/fluentd
    volumes:
      - ./Cellar.Hub.Log/fluentd/conf:/fluentd/etc
    # depends_on: 
    #   - elasticsearch
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch
    volumes:
        - /data/cellarstone.hub/elasticsearch:/var/lib/elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  prometheus:
    image: cellar.prometheus
    build:
      context: ./Cellar.Hub.Log/prometheus
      dockerfile: Dockerfile
    volumes:
      - /data/cellarstone.hub/prometheus:/prometheus
    ports:
      - '9090:9090'
    depends_on: 
      - pushgateway
    links:
      - pushgateway
    
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana
    volumes:
      - /data/cellarstone.hub/grafana:/var/lib/grafana
    ports:
      - '3000:3000'
