version: '2'

services:
  cellar.hub.web:
    image: cellar.hub.web
    build:
      context: ./Cellar.Hub.Web
      dockerfile: Dockerfile

  cellar.hub.dataflow:
    image: cellar.hub.dataflow
    build:
      context: ./Cellar.Hub.DataFlow
      dockerfile: Dockerfile
    links:
      - cellar.hub.sql

  cellar.hub.sql:
    image: cellar.hub.sql
    build: 
      context: ./Cellar.Hub.Sql
      dockerfile: Dockerfile
    ports:
    - "5434:5432"

  broker:
    image: cellar.hub.mqtt
    build: 
      context: ./Cellar.Hub.Mqtt
      dockerfile: Dockerfile
    ports:
    - "1883:1883"
