// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	CellarUser
	GetAllUsersRequest
	GetAllUsersResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OBJECTS
type CellarUser struct {
	Id    string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	State string `protobuf:"bytes,3,opt,name=State" json:"State,omitempty"`
	Image string `protobuf:"bytes,4,opt,name=Image" json:"Image,omitempty"`
}

func (m *CellarUser) Reset()                    { *m = CellarUser{} }
func (m *CellarUser) String() string            { return proto.CompactTextString(m) }
func (*CellarUser) ProtoMessage()               {}
func (*CellarUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CellarUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CellarUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CellarUser) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CellarUser) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type GetAllUsersRequest struct {
}

func (m *GetAllUsersRequest) Reset()                    { *m = GetAllUsersRequest{} }
func (m *GetAllUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllUsersRequest) ProtoMessage()               {}
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetAllUsersResponse struct {
	Data []*CellarUser `protobuf:"bytes,1,rep,name=Data" json:"Data,omitempty"`
}

func (m *GetAllUsersResponse) Reset()                    { *m = GetAllUsersResponse{} }
func (m *GetAllUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllUsersResponse) ProtoMessage()               {}
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetAllUsersResponse) GetData() []*CellarUser {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CellarUser)(nil), "pb.CellarUser")
	proto.RegisterType((*GetAllUsersRequest)(nil), "pb.GetAllUsersRequest")
	proto.RegisterType((*GetAllUsersResponse)(nil), "pb.GetAllUsersResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error) {
	out := new(GetAllUsersResponse)
	err := grpc.Invoke(ctx, "/pb.UserService/GetAllUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	GetAllUsers(context.Context, *GetAllUsersRequest) (*GetAllUsersResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllUsers(ctx, req.(*GetAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllUsers",
			Handler:    _UserService_GetAllUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0x6b, 0xd9, 0x2d, 0xf4, 0x0c, 0x1e, 0xae, 0xa6, 0x15, 0x9d, 0x8c, 0x26, 0x4f, 0x1e,
	0xdc, 0xa9, 0x5b, 0x4b, 0x0b, 0xc5, 0x4b, 0x0b, 0x36, 0xdd, 0xb2, 0xc8, 0xf1, 0x11, 0x02, 0x72,
	0xac, 0x48, 0x72, 0x7e, 0x7f, 0x90, 0x3c, 0x24, 0xc1, 0x9b, 0xbe, 0x4f, 0xdc, 0x7b, 0xc7, 0x01,
	0xcc, 0x96, 0x4c, 0xa5, 0xcd, 0xe4, 0x26, 0x64, 0xba, 0x17, 0x1b, 0x80, 0x2f, 0x52, 0x4a, 0x9a,
	0x7f, 0x4b, 0x06, 0x33, 0x60, 0xcd, 0xc0, 0xa3, 0x22, 0x2a, 0x1f, 0x5b, 0xd6, 0x0c, 0x88, 0x90,
	0xfc, 0xca, 0x91, 0x38, 0x0b, 0x26, 0xbc, 0x31, 0x87, 0xfb, 0xce, 0x49, 0x47, 0x3c, 0x0e, 0x72,
	0x01, 0x6f, 0x9b, 0x51, 0xee, 0x88, 0x27, 0x8b, 0x0d, 0x20, 0x72, 0xc0, 0x1f, 0x72, 0x9f, 0x4a,
	0xf9, 0x74, 0xdb, 0xd2, 0x71, 0x26, 0xeb, 0xc4, 0x3b, 0x3c, 0xdd, 0x58, 0xab, 0xa7, 0x83, 0x25,
	0x14, 0x90, 0x7c, 0x4b, 0x27, 0x79, 0x54, 0xc4, 0x65, 0x5a, 0x67, 0x95, 0xee, 0xab, 0xcb, 0x6a,
	0x6d, 0xf8, 0xab, 0xff, 0x20, 0xf5, 0xd4, 0x91, 0x39, 0xed, 0xb7, 0x84, 0x1f, 0x90, 0x5e, 0x25,
	0xe1, 0xb3, 0x9f, 0x59, 0x17, 0xbe, 0xbe, 0xac, 0xfc, 0x52, 0x29, 0xee, 0xfa, 0x87, 0x70, 0x8a,
	0xb7, 0x73, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xfe, 0x87, 0xf6, 0x18, 0x01, 0x00, 0x00,
}
