################################################################
# Global configuration
################################################################
logLevel = "ERROR"

# Set HTTP Entrypoint that redirects to HTTPS
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/ssl/traefik/cellarstonehub.crt"
      keyFile = "/etc/ssl/traefik/cellarstonehub.key"
      [[entryPoints.https.tls.certificates]]
      certFile = """-----BEGIN CERTIFICATE-----
                      <cert file content>
                      -----END CERTIFICATE-----"""
      keyFile = """-----BEGIN CERTIFICATE-----
                      <key file content>
                      -----END CERTIFICATE-----"""
    [entryPoints.other-https]
    address = ":4443"
      [entryPoints.other-https.tls]


################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"

################################################################
# Docker configuration backend
################################################################
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
# Default: "unix:///var/run/docker.sock"
#
# endpoint = "tcp://10.10.10.10:2375"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Optional
# Default: ""
#
domain = "cellarstone.hub"

# Expose containers by default in traefik
#
# Optional
# Default: true
#
# exposedbydefault = true